name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r technical_agent/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 technical_agent
      - name: Run and Validate Script Output
        run: |
          python3 technical_agent/main.py AOT.BK | jq -e '
            .trend | type == "string" and
            .rsi | type == "number" and
            .macd_line | type == "number" and
            .macd_signal | type == "number" and
            .signal | type == "string" and
            .reasoning | type == "string"
          '
